language: android

jdk:
  - oraclejdk8
  
android:
  components:
    - platform-tools
    - tools
    - extra-android-m2repository
    - android-24
    - build-tools-24.0.1
    
script:
  - ./gradlew clean test
