language: android

jdk:
  - oraclejdk7
  
android:
  components:
    - platform-tools
    - tools
    - extra-android-m2repository
    - android-23
    - build-tools-23.0.3
    
script:
  - ./gradlew clean test
